### ISSUE TITLE
npm package of new version 1.27.0 has no dist/ folder anymore

### ISSUE THREAD

**Issue by httpdigest** [mobileposse/auto-delete-bucket#8]
The new version 1.27.0 cannot be used, because the dist/ directory in its distribution is missing (which is referred by the package.json's "main" attribute as `dist/src/resource/auto-delete-bucket.js`), therefore ES6 imports `import { AutoDeleteBucket } from '@mobileposse/auto-delete-bucket'` fail.

**Comment by psigen** [comment]
Confirming this.  Perhaps a `publish` was done without a successful `build`?

This can be verified as not a local issue using the RunKit demo on npm itself:
https://npm.runkit.com/%40mobileposse%2Fauto-delete-bucket

Clicking `run` immediately errors with:
```
Error: Cannot find module '@mobileposse/auto-delete-bucket'
```

**Comment by BDQ** [comment]
Yeah, my bad - I'll do a new release now.

**Comment by BDQ** [comment]
I'm getting a bunch of errors from `tsc`

> node_modules/@aws-cdk/core/lib/cfn-parameter.d.ts:100:9 - error TS1086: An accessor cannot be declared in an ambient context.

Explains the bad build for 1.27.0, looking into a fix for these now.

**Comment by BDQ** [comment]
Ok, `1.28.0` is released & solid.
